[build]
  command = "bun run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/__nextjs"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
